### PR TITLE
Add Logic to the game

### PR DESCRIPTION
**Pull request by elmejdki**
- First, we developed the TicTacToe class the contain the logic,
- Then, we put used that logic inside our main file that contains the workflow.

### CODE REVIEW

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @elmejdki and @javierbotero :balloon: :lollipop: 

### You've done a good job so far, I think asking for the players's names makes your game user friendly so please keep it :video_game: sadly I couldn't play the game far from the first move so please pay attention to these changes :point_down: 

#### Behavior

I couldn't try none of this behavior because as I mentioned before the game breaks after the first move, so make sure to check all of these  works before submitting again for a code review

image

- [ ] The application does not allow a player to move into an occupied position
- [ ] The application does not exit due to invalid input - it informs the player about it and asks for their move again
- [ ] The application saves players' move and displays the status of the board after that
- [ ] The application can determine if the move is a winning move
- [ ]  The application can detect a sequence of three horizontal elements that are equal
- [ ] The application can detect a sequence of three vertical elements that are equal
- [ ] The application can detect a sequence of three equal elements in a diagonal from left and right to right
- [ ] The application can tell if there was a draw after players move
- [ ] The application can change active player
- [ ] I can see your game request for each of the players' name, but your game is letting the players have empty names and also the same name, so let's add the validations to avoid this to happen
image

#### Implementation details

* [ ] The project uses at least two classes (Usually it uses three: Game, Board and Player). The code of the project should be logically divided between classes. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/classes.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

- You have one class named logic that's good let's add another one at least :muscle: 

* [ ] The code should respect the single responsibility rule for methods (i.e. each method does exactly one thing). ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/single_responsibility.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

- All the methods in your main.rb file doesn't respect this rule, I advise not to use methods here and just keep a loop of the game within the main.rb file calling objects and methods from the classes you created.

### That's it, team! :raised_hands: 

### Please :pray: do the changes :man_technologist: :man_technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? please contact me on slack first **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Your project looks :+1: amazing!
One more thing left to change:
* [ ] Use attr_readers/attr_writers instead of attr_accessors. By using it you allow writing that property from outside the class. That variable can be set to anything. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/attr_accessor.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

### Please kindly fix the above issue and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Great  work, Congratulation :+1: Project Approved.
You did all changes required previously. Go ahead and merge to develop.
_Goodluck in your next milestone_ *Happy coding*

**Pull request merged**
