### PR TITLE
Readme game instructions

### PR DESCRIPTION
**Pull request by elmejdki**
create a readme file and fill it with informations and instructions about the game

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @elmejdki        
#### Great Job so far, but there are a few more things required. 
### General
- [ ]  Your README file should explicitly tell me  how to start the game.for example
-  where to navigate to  
-  what file to run to get the game started
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by Anna-Myzukina** [comment]
## Hi team ! :wave: 

# Status: [changes required]


### Good job with the milestone. Few steps and your project can be approved:
`Implementation details`


*  The code of the project should be logically divided between classes.(Usually it uses three: Game, Board and Player) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/). 
screenshot 

* All classes are kept in lib directory from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/). 
screenshot 

* The code should respect the single responsibility rule for methods (i.e. each method does exactly one thing). You don`t need to create long methods that are doing multiple steps of the game process from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/). 
screenshot 

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding * <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">computer</g-emoji>

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Hi Team,
### README file looks amazing. Congratulation :+1: Approved.
Go ahead and merge to develop.
_Goodluck in your next project_ *Happy coding*

**Pull request merged**
